apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace/openshift-gitops-operator.yaml
- operator/openshift-gitops-operator.yaml
- gitops/app/demo-application.yaml
- gitops/infra/kyverno.yaml
- gitops/infra/pipelines.yaml
- gitops/infra/policies.yaml
- gitops/infra/onboarding.yaml
- gitops/rbac/cluster-role-gitops.yaml
- gitops/rbac/cluster-rolebinding-gitops.yaml
- gitops/rbac/cluster-role-priviledged.yaml
- gitops/rbac/cluster-rolebinding-kyverno.yaml

