apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: cluster-primer/gitops/rbac/overlays/default
    repoURL: 'https://github.com/anyaegbufrancis/openprep.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
