apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-app
    app.kubernetes.io/component: demo-app
    app.kubernetes.io/instance: demo-app
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: demo-app
  namespace: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        deployment: demo-app
    spec:
      containers:
      - image: 'quay.io/fanyaegb/demo-app:1.0'
        name: 'demo-app'
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}