apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: 01-cluster-primer/2-operator-prep/base/resources/2-operators/openshift-pipelines/overlays/default
    repoURL: 'https://github.com/anyaegbufrancis/openprep.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
     syncOptions:
        - CreateNamespace=true
     automated:
        prune: false
        selfHeal: true
