apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-application
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: 'demo-app'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/application/app-argo/overlays/default
    repoURL: 'https://github.com/anyaegbufrancis/openprep.git'
    targetRevision: HEAD
    directory:
      recurse: true  
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true